services:
  - type: web
    name: ai-career-compass
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
